### ISSUE TITLE
iptables not correctly configured on CentOS 8 host

### ISSUE THREAD

**Issue by SwimilTylers** [oecp/rama#29]
Bug Report
---

Type: *bug report*

### What happened

An compatibility problem might it be.

I set up a k8s cluster with CentOS 8 (which links `iptables` to `nftables`) and runs pods on Overlay and Underlay networks. I observed that on the host machines,  the cmd `lsmod | grep ip_tables` shows that ip_tables is used by iptable_nat, iptable_mangle, and iptable_filter.

After checking the logs of daemon pods, I believe the iptables rule is written without error. But on host machine, no rama-related iptables rules shown through either `iptables-save` or `nft rule list`.

To be mentioned, `iptables-save` warns that there are more rules on iptables-legacy.

### What you expected to happen

I should observe rama-related rules in `iptables-save`.

### How to reproduce it (as minimally and precisely as possible)

Set up a k8s cluster CentOS 8 nodes. Install rama and run several Overlay/Underlay pods.

### Anything else we need to know?

CentOS 8 removes iptables from packages and links it to nftables.

Kube-proxy works perfectly.

### Environment
- rama version: v1
- OS (e.g. `cat /etc/os-release`): CentOS 8
- Kernel (e.g. `uname -a`): Linux 4.18.0-305.7.1.el8_4.x86_6
- Kubernetes version: v1.21.

**Comment by mars1024** [comment]
Thanks for your patience, could you help to paste more outputs here? Such as logs, iptables-save...

**Comment by SwimilTylers** [comment]
Here is my pods status. 10.14.100.0/24 is my overlay subnet, while 192.168.56.0/24 is the underlay of mine.

```
[admin@master-node ~]$ kubectl get pods -owide
NAME                             READY   STATUS    RESTARTS   AGE   IP              NODE     NOMINATED NODE   READINESS GATES
curl-overlay-cc54b95cc-5j6ch     1/1     Running   0          24h   10.14.100.10    node-1   <none>           <none>
curl-overlay-cc54b95cc-kwngr     1/1     Running   0          24h   10.14.100.11    node-1   <none>           <none>
curl-overlay-cc54b95cc-w4kvl     1/1     Running   0          24h   10.14.100.12    node-1   <none>           <none>
curl-underlay-6bfc4f74dd-d4q7h   1/1     Running   0          24h   192.168.56.13   node-1   <none>           <none>
curl-underlay-6bfc4f74dd-n8b54   1/1     Running   0          24h   192.168.56.12   node-1   <none>           <none>
curl-underlay-6bfc4f74dd-xng6q   1/1     Running   0          24h   192.168.56.11   node-1   <none>           <none>
hello-overlay-7c8464b6cc-4557t   1/1     Running   0          24h   10.14.100.14    node-1   <none>           <none>
hello-overlay-7c8464b6cc-rjtdb   1/1     Running   0          24h   10.14.100.13    node-1   <none>           <none>
hello-overlay-7c8464b6cc-wjdnk   1/1     Running   0          24h   10.14.100.15    node-1   <none>           <none>
```

Here is rama related entries of`iptables-save` on node-1:

```
[admin@node-1 ~]$ sudo iptables-save | grep -i RAMA
-A KUBE-SERVICES -d 10.108.2.43/32 -p tcp -m comment --comment "kube-system/rama-webhook:webhook-port cluster IP" -m tcp --dport 443 -j KUBE-SVC-JPPFOI7P5T62DDAU
# Warning: iptables-legacy tables present, use iptables-legacy-save to see them
-A KUBE-SVC-JPPFOI7P5T62DDAU -m comment --comment "kube-system/rama-webhook:webhook-port" -j KUBE-SEP-FYPKJJVT7BDRAATJ
-A KUBE-SEP-FYPKJJVT7BDRAATJ -s 192.168.57.3/32 -m comment --comment "kube-system/rama-webhook:webhook-port" -j KUBE-MARK-MASQ
-A KUBE-SEP-FYPKJJVT7BDRAATJ -p tcp -m comment --comment "kube-system/rama-webhook:webhook-port" -m tcp -j DNAT --to-destination 192.168.57.3:9898
```

I draw the log from the daemon pod on nodes-1 and find nothing related to iptables settings:

```
[admin@master-node ~]$ kubectl logs rama-daemon-v5cqj -n kube-system  | grep -i fail
E0708 09:14:25.999440   21333 controller.go:361] overlay proxy neigh failed: no matched node or pod ip cache found for ip 192.168.56.1
E0709 11:55:01.865491   21333 controller.go:361] overlay proxy neigh failed: no matched node or pod ip cache found for ip 192.168.56.1
E0709 11:55:33.521743   21333 controller.go:361] overlay proxy neigh failed: no matched node or pod ip cache found for ip 192.168.56.1
E0709 11:56:28.930568   21333 controller.go:361] overlay proxy neigh failed: no matched node or pod ip cache found for ip 192.168.56.1
E0709 11:58:32.546499   21333 controller.go:361] overlay proxy neigh failed: no matched node or pod ip cache found for ip 192.168.56.1
```

PS: `192.168.56.1` is my gateway of underlay network.

**Comment by mars1024** [comment]
Thanks, could you help to grep all error logs? `grep E0709`? We believe that iptables module must exit for some reason before executing.

**Comment by hhyasdf** [comment]
We do need an enhancement to adapt to `nftables` as what kube-proxy has done. 

Pr of kubernetes is https://github.com/kubernetes/kubernetes/pull/82966

Related Kubernetes issue https://github.com/kubernetes/kubernetes/issues/71305

**Comment by SwimilTylers** [comment]
> Thanks, could you help to grep all error logs? `grep E0709`? We believe that iptables module must exit for some reason before executing.

Of course.

Here are daemons' logs
```
[admin@master-node ~]$ kubectl logs rama-daemon-v5cqj -n kube-system  | grep -i E0709
E0709 11:55:01.865491   21333 controller.go:361] overlay proxy neigh failed: no matched node or pod ip cache found for ip 192.168.56.1
E0709 11:55:33.521743   21333 controller.go:361] overlay proxy neigh failed: no matched node or pod ip cache found for ip 192.168.56.1
E0709 11:56:28.930568   21333 controller.go:361] overlay proxy neigh failed: no matched node or pod ip cache found for ip 192.168.56.1
E0709 11:58:32.546499   21333 controller.go:361] overlay proxy neigh failed: no matched node or pod ip cache found for ip 192.168.56.1
[admin@master-node ~]$ kubectl logs rama-daemon-tvvv6 -n kube-system  | grep -i E0709
E0709 00:44:15.681072   17270 controller.go:361] overlay proxy neigh failed: no matched node or pod ip cache found for ip 10.14.100.6
```
 So you can see, no related error found in there.
